### ISSUE TITLE
[META] Make sure we fully respect the grading criteria

### ISSUE THREAD

**Issue by Arthur2479** [HEIG-VD-DAI-Iseni-Jacobs/pictures-cli-editor#16]
Fetched from [here](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/07-practical-work-1/COURSE_MATERIAL.md#grading-criteria)

### Category 1 - Meta

- [x] The whole team contributes to the project and can explain it in details to share knowledge between the team
- [x] A GitHub Discussion is opened during the first week of the project to explain the idea of the project so the teachers can validate the idea
- [x] The GitHub Discussion is updated with the link to the repository and a related commit hash before the deadline - every 24 hours after the deadline will result in a -1 point penalty on the final grade

### Category 2 - Git, GitHub and Markdown

- [x] Issues are created all along the project to describe new features, elements to improve, etc. to plan work
- [x] Pull requests linked to the Issues are created, discussed and reviewed all along the project to integrate new work iteratively
- [x] The issue, pull request and commit messages are descriptive so a new comer can understand what has been done
- [x] The commits are signed to increase the security and the confidence of the project
- [x] The repository contains a gitignore file to ignore all unwanted files (Maven output, IntelliJ IDEA files related to local computer, etc.) to keep the repository clean/small and to avoid security leaks
- [x] The README is well structured and explains the purpose of your application so new users can understand it
- [x] The README explains how to use your application with examples and outputs so a new user/developer can understand your application without having to run it locally
- [x] The README describes explicit commands to clone and build your application with Git and Maven so new developers can start and develop your project on their own computer
- [x] The repository contains meaningful example files to allow new users/developers (such as the teaching staff) to try out your application locally - these files can be the same as the ones used in the examples and outputs snippets

### Category 3 - Java, IntelliJ IDEA and Maven

- [x] The codebase is well structured, easy to access, easy to understand and is documented so it is easier for new comers to understand the codebase
- [x] The codebase contains the two IntelliJ IDEA configuration files ("Run the application" and "Package application as JAR file") so developers can run and build the application within their IDE
- [x] The codebase contains the Maven wrapper configuration file and scripts so developers can build the application without an IDE and without having to install Maven
- [x] The codebase is built with Maven and outputs an executable JAR file so the application can be ran everywhere Java is installed

### Category 4 - Java IOs

- [x] The CLI displays a comprehensive help message on how to use the application and displays errors on invalid/missing inputs and/or processing errors
- [x] The CLI takes some mandatory arguments and other optional arguments for customization
- [x] The CLI processes the files efficiently
- [x] The CLI processes the files so that they are compatible across operating systems/languages
- [x] The CLI correctly manages resources in case a problem occurs when processing the files
- [x] The CLI correctly processes the input file and writes the result in the output file with its execution time

### Category 5 - Presentation and questions

- [x] The application is presented and a demo is made as you would do it to a colleague/another team/boss/client/investor so they can understand what you created, why and how
- [x] The presentation is clear and well prepared - everyone speaks during the presentation
- [ ] The answers to the questions are correct

### Constraints reminder:

- [x] The application must be written in Java, compatible with Java 21
- [x] The application must be built using Maven with the maven-shade-plugin plugin
- [x] The application must use the picocli dependency
- [x] You can only use the Java classes seen in the course to process the files (you can use other libraries to help you once the files are opened) - See the [External dependencies](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/07-practical-work-1/COURSE_MATERIAL.md#external-dependencies) section
- [x] Your application must be slightly more complex and slightly different than the examples presented during the course (we emphasize the word slightly, no need to shoot for the moon!)
